name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: {python-version: 3.10}
      - run: pip install black flake8 isort mypy
      - run: black --check .
      - run: isort --check-only .
      - run: flake8 src
      - run: mypy src

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: {python-version: ${{ matrix.python }}}
      - run: pip install poetry && poetry install
      - run: pytest --cov=src
      - run: coverage report